-- ============================================
-- Xaweed Shop — Seed Data
-- Run this in Supabase SQL Editor AFTER schema.sql
-- ============================================

-- ─── Categories ───────────────────────────
INSERT INTO categories (id, name, slug, description, image, sort_order) VALUES
  ('flower', 'Flower', 'flower', 'Premium indoor & outdoor strains, fresh daily', '/images/products/strains/cajan-mintz.jpeg', 1),
  ('edible', 'Edibles', 'edibles', 'KANHA infused gummies & treats', '/images/products/edibles/kanha-galactic-grape.jpeg', 2),
  ('pre-roll', 'Pre-Rolls', 'pre-rolls', 'Hand-rolled joints, ready to smoke', '/images/preRoll.jpg', 3),
  ('accessory', 'Accessories', 'accessories', 'Bongs, grinders, papers & more', '/images/products/bongs/acrylic-bong.jpeg', 4);

-- ─── Products: Flowers ────────────────────
INSERT INTO products (id, name, slug, category, short_description, long_description, price_display, price_value, image, images, tags, featured, in_stock, line_inquiry_text, strain, thc_content, weight, effects, sort_order) VALUES
  ('cajan-mintz', 'Cajan Mintz', 'cajan-mintz', 'flower', 'Minty hybrid — cool menthol finish, heavy hitter', 'Cajan Mintz delivers a unique minty terpene profile with a powerful THC punch. Dense, frosty nugs with a cool menthol exhale and deep body relaxation.', '฿200 / 1g', 200, '/images/products/strains/cajan-mintz.jpeg', ARRAY['/images/products/strains/cajan-mintz.jpeg', '/images/products/strains/cajan-mintz-alt.jpeg'], ARRAY['hybrid', 'minty', 'potent', 'indoor'], true, true, 'Hi! I''d like to order Cajan Mintz.', 'hybrid', 'High', '1g / 10g', ARRAY['Relaxed', 'Euphoric', 'Tingly', 'Happy'], 1),
  ('code-red', 'Code Red', 'code-red', 'flower', 'Indica-leaning — deep red hairs, knockout potency', 'Code Red is a heavy-hitting indica-leaning hybrid covered in fiery red pistils. Expect a full-body melt with earthy berry undertones.', '฿200 / 1g', 200, '/images/products/strains/code-red.jpeg', ARRAY['/images/products/strains/code-red.jpeg', '/images/products/strains/code-red-alt.jpeg'], ARRAY['indica', 'potent', 'berry', 'indoor'], true, true, 'Hi! I''d like to order Code Red.', 'indica', 'Very High', '1g / 10g', ARRAY['Sleepy', 'Relaxed', 'Hungry', 'Euphoric'], 2),
  ('miami-vice', 'Miami Vice', 'miami-vice', 'flower', 'Sativa-dominant — tropical, fruity, uplifting high', 'Miami Vice brings the sunshine with bright tropical flavours and an energising cerebral high. Perfect for social sessions and creative flow.', '฿200 / 1g', 200, '/images/products/strains/miami-vice.jpeg', ARRAY['/images/products/strains/miami-vice.jpeg', '/images/products/strains/miami-vice-alt.jpeg'], ARRAY['sativa', 'tropical', 'fruity', 'uplifting'], true, true, 'Hi! I''d like to order Miami Vice.', 'sativa', 'High', '1g / 10g', ARRAY['Euphoric', 'Energetic', 'Creative', 'Happy'], 3),
  ('top-banana-fritter', 'Top Banana Fritter', 'top-banana-fritter', 'flower', 'Hybrid — creamy banana dessert terps, balanced high', 'Top Banana Fritter is a premium dessert strain with rich banana-cream flavour. Perfectly balanced between head and body for an all-day smoke.', '฿200 / 1g', 200, '/images/products/strains/top-banana-fritter.jpeg', ARRAY['/images/products/strains/top-banana-fritter.jpeg', '/images/products/strains/top-banana-fritter-alt.jpeg'], ARRAY['hybrid', 'dessert', 'banana', 'top-shelf'], true, true, 'Hi! I''d like to order Top Banana Fritter.', 'hybrid', 'High', '1g / 10g', ARRAY['Happy', 'Relaxed', 'Creative', 'Euphoric'], 4),
  ('dosidos', 'Do-Si-Dos', 'dosidos', 'flower', 'Indica — lime & mint cookies, deep relaxation', 'Do-Si-Dos is a potent indica with OGKB x GSC genetics. Expect earthy lime and mint cookie flavours with a powerful sedative body high.', '฿180 / 1g', 180, '/images/products/strains/dosidos.jpeg', '{}', ARRAY['indica', 'cookies', 'potent', 'indoor'], false, true, 'Hi! I''d like to order Do-Si-Dos.', 'indica', 'Very High', '1g / 10g', ARRAY['Sleepy', 'Relaxed', 'Euphoric', 'Body High'], 5),
  ('double-up', 'Double Up', 'double-up', 'flower', 'Hybrid — double the terps, double the vibes', 'Double Up is a flavour-packed hybrid with a complex terpene profile. Smooth smoke with a balanced, mood-lifting effect.', '฿180 / 1g', 180, '/images/products/strains/double-up.jpeg', '{}', ARRAY['hybrid', 'smooth', 'balanced', 'indoor'], false, true, 'Hi! I''d like to order Double Up.', 'hybrid', 'High', '1g / 10g', ARRAY['Creative', 'Happy', 'Relaxed', 'Social'], 6),
  ('granpa-cookies', 'Grandpa Cookies', 'granpa-cookies', 'flower', 'Indica — classic cookie genetics, couch-lock vibes', 'Grandpa Cookies brings old-school cookie genetics with a modern twist. Dense, resinous buds with sweet dough flavour and heavy indica effects.', '฿180 / 1g', 180, '/images/products/strains/granpa-cookies.jpeg', '{}', ARRAY['indica', 'cookies', 'classic', 'indoor'], false, true, 'Hi! I''d like to order Grandpa Cookies.', 'indica', 'High', '1g / 10g', ARRAY['Sleepy', 'Hungry', 'Relaxed', 'Cozy'], 7),
  ('guava-bomba', 'Guava Bomba', 'guava-bomba', 'flower', 'Sativa — tropical guava explosion, uplifting', 'Guava Bomba bursts with sweet tropical guava terps. A sativa-leaning strain perfect for daytime with energising and creative effects.', '฿180 / 1g', 180, '/images/products/strains/guava-bomba.jpeg', '{}', ARRAY['sativa', 'tropical', 'fruity', 'daytime'], false, true, 'Hi! I''d like to order Guava Bomba.', 'sativa', 'Medium-High', '1g / 10g', ARRAY['Energetic', 'Creative', 'Happy', 'Focused'], 8),
  ('pineapple-gelato', 'Pineapple Gelato', 'pineapple-gelato', 'flower', 'Hybrid — sweet pineapple gelato, smooth & potent', 'Pineapple Gelato combines Gelato genetics with tropical pineapple terps. Creamy smooth smoke with a balanced euphoric high.', '฿180 / 1g', 180, '/images/products/strains/pineapple-gelato.jpeg', '{}', ARRAY['hybrid', 'gelato', 'tropical', 'smooth'], false, true, 'Hi! I''d like to order Pineapple Gelato.', 'hybrid', 'High', '1g / 10g', ARRAY['Euphoric', 'Happy', 'Relaxed', 'Creative'], 9),
  ('purple-gas-mask', 'Purple Gas Mask', 'purple-gas-mask', 'flower', 'Indica — deep purple, gassy nose, knockout punch', 'Purple Gas Mask is a visually stunning indica with deep purple colouring and a pungent gas aroma. Heavy-hitting for experienced smokers.', '฿200 / 1g', 200, '/images/products/strains/purple-gas-mask.jpeg', '{}', ARRAY['indica', 'premium', 'gassy', 'purple'], false, true, 'Hi! I''d like to order Purple Gas Mask.', 'indica', 'Very High', '1g / 10g', ARRAY['Sleepy', 'Relaxed', 'Euphoric', 'Pain Relief'], 10),
  ('subzero-cherry', 'Subzero Cherry', 'subzero-cherry', 'flower', 'Hybrid — icy cherry terps, frosty trichomes', 'Subzero Cherry is dripping with trichomes and bursting with sweet cherry flavour. A balanced hybrid for any occasion.', '฿180 / 1g', 180, '/images/products/strains/subzero-cherry.jpeg', '{}', ARRAY['hybrid', 'fruity', 'cherry', 'frosty'], false, true, 'Hi! I''d like to order Subzero Cherry.', 'hybrid', 'High', '1g / 10g', ARRAY['Happy', 'Euphoric', 'Relaxed', 'Uplifting'], 11),
  ('supreme-oreoz', 'Supreme Oreoz', 'supreme-oreoz', 'flower', 'Indica — cookies & cream flavour, heavy hitter', 'Supreme Oreoz is a dessert lover''s dream with rich chocolate and cream terps. Dense indica buds that deliver deep body relaxation.', '฿200 / 1g', 200, '/images/products/strains/supreme-oreoz.jpeg', '{}', ARRAY['indica', 'dessert', 'premium', 'indoor'], false, true, 'Hi! I''d like to order Supreme Oreoz.', 'indica', 'Very High', '1g / 10g', ARRAY['Sleepy', 'Relaxed', 'Hungry', 'Euphoric'], 12),
  ('west-coast-diesel', 'West Coast Diesel', 'west-coast-diesel', 'flower', 'Sativa — diesel fuel nose, energising cerebral high', 'West Coast Diesel is a classic sativa with sharp diesel aromatics and an electric cerebral buzz. Ideal for wake-and-bake sessions.', '฿180 / 1g', 180, '/images/products/strains/west-coast-diesel.jpeg', '{}', ARRAY['sativa', 'diesel', 'classic', 'energising'], false, true, 'Hi! I''d like to order West Coast Diesel.', 'sativa', 'High', '1g / 10g', ARRAY['Energetic', 'Focused', 'Creative', 'Uplifting'], 13),
  ('top-snow-ball', 'Top Snow Ball', 'top-snow-ball', 'flower', 'Indoor Sativa 100% — frosty, potent, premium', 'Top Snow Ball is a premium indoor-grown Sativa strain known for its dense, crystal-coated buds and uplifting cerebral effects.', '฿200 / 1g', 200, '/images/products/top-snow-ball.jpg', '{}', ARRAY['sativa', 'indoor', 'premium', 'top-shelf'], false, true, 'Hi! I''d like to order Top Snow Ball.', 'sativa', 'High', '1g / 10g', ARRAY['Euphoric', 'Creative', 'Energetic', 'Uplifting'], 14),
  ('top-papaya-fiya', 'Top Papaya Fiya', 'top-papaya-fiya', 'flower', 'Indoor hybrid — tropical flavour, smooth high', 'Top Papaya Fiya is a flavourful indoor hybrid with tropical papaya notes and a beautifully balanced high. Perfect for any time of day.', '฿80 / 1g', 80, '/images/products/top-papaya-fiya.jpg', '{}', ARRAY['hybrid', 'indoor', 'tropical', 'smooth'], false, true, 'Hi! I''d like to order Top Papaya Fiya.', 'hybrid', 'Medium-High', '1g / 10g', ARRAY['Relaxed', 'Happy', 'Creative', 'Chill'], 15),
  ('og-kush-premium', 'OG Kush Premium', 'og-kush-premium', 'flower', 'Classic indica-dominant — earthy, piney, potent', 'A legendary strain with deep earthy and pine aromas. Our OG Kush Premium delivers heavy relaxation with a euphoric mental buzz.', '฿150 / 1g', 150, '/images/products/og-kush.jpg', '{}', ARRAY['indica', 'classic', 'potent', 'earthy'], false, true, 'Hi! I''d like to order OG Kush Premium.', 'indica', 'High', '1g / 10g', ARRAY['Relaxed', 'Euphoric', 'Sleepy', 'Hungry'], 16),
  ('mango-haze', 'Mango Haze', 'mango-haze', 'flower', 'Sativa-dominant — sweet mango aroma, uplifting', 'Mango Haze brings tropical sweetness with a clear-headed, energising sativa effect. Great for daytime use and creative sessions.', '฿120 / 1g', 120, '/images/products/mango-haze.jpg', '{}', ARRAY['sativa', 'tropical', 'daytime', 'sweet'], false, true, 'Hi! I''d like to order Mango Haze.', 'sativa', 'Medium', '1g / 10g', ARRAY['Energetic', 'Happy', 'Creative', 'Focused'], 17);

-- ─── Products: Edibles ────────────────────
INSERT INTO products (id, name, slug, category, short_description, long_description, price_display, price_value, image, images, tags, featured, in_stock, line_inquiry_text, brand, effects, price_options, sort_order) VALUES
  ('kanha-galactic-grape', 'KANHA Galactic Grape', 'kanha-galactic-grape', 'edible', 'THC gummy — grape flavour, galactic good vibes', 'KANHA Galactic Grape gummies deliver out-of-this-world grape flavour with consistent, reliable THC dosing. Perfect for a chill night in.', '฿165', 165, '/images/products/edibles/kanha-galactic-grape.jpeg', ARRAY['/images/products/edibles/kanha-galactic-grape.jpeg', '/images/products/edibles/kanha-galactic-grape-details.jpeg'], ARRAY['edible', 'gummy', 'grape', 'thc'], false, true, 'Hi! I''d like to order KANHA Galactic Grape.', 'KANHA', ARRAY['Relaxed', 'Happy', 'Euphoric', 'Giggly'], '[{"label": "1 pack", "price": 165}]', 18),
  ('kanha-watermelon-hybrid', 'KANHA Watermelon Hybrid', 'kanha-watermelon-hybrid', 'edible', 'Hybrid gummy — juicy watermelon, balanced effects', 'KANHA Watermelon Hybrid gummies combine sweet watermelon flavour with perfectly balanced hybrid effects. Great for first-timers and experienced users alike.', '฿165', 165, '/images/products/edibles/kanha-watermelon-hybrid.jpeg', ARRAY['/images/products/edibles/kanha-watermelon-hybrid.jpeg', '/images/products/edibles/kanha-watermelon-details.jpeg'], ARRAY['edible', 'gummy', 'watermelon', 'hybrid'], true, true, 'Hi! I''d like to order KANHA Watermelon Hybrid.', 'KANHA', ARRAY['Balanced', 'Relaxed', 'Happy', 'Chill'], '[{"label": "1 pack", "price": 165}]', 19),
  ('kanha-tranquility-blueberry', 'KANHA Tranquility Blueberry', 'kanha-tranquility-blueberry', 'edible', 'CBD+THC gummy — blueberry calm, sleep aid', 'KANHA Tranquility Blueberry gummies blend CBD and THC for serene relaxation. Sweet blueberry flavour with calming effects perfect for winding down.', '฿165', 165, '/images/products/edibles/kanha-tranquility-blueberry.jpeg', ARRAY['/images/products/edibles/kanha-tranquility-blueberry.jpeg', '/images/products/edibles/kanha-tranquility-details.jpeg'], ARRAY['edible', 'gummy', 'blueberry', 'cbd', 'sleep'], false, true, 'Hi! I''d like to order KANHA Tranquility Blueberry.', 'KANHA', ARRAY['Calm', 'Sleepy', 'Relaxed', 'Peaceful'], '[{"label": "1 pack", "price": 165}]', 20),
  ('kanha-love-raspberry', 'KANHA Love Raspberry', 'kanha-love-raspberry', 'edible', 'Aphrodisiac gummy — raspberry love, feel-good vibes', 'KANHA Love Raspberry gummies are infused with mood-enhancing botanicals and sweet raspberry flavour for a feel-good social experience.', '฿165', 165, '/images/products/edibles/kanha-love-raspberry.jpeg', ARRAY['/images/products/edibles/kanha-love-raspberry.jpeg', '/images/products/edibles/kanha-love-raspberry-details.jpeg'], ARRAY['edible', 'gummy', 'raspberry', 'love', 'social'], false, true, 'Hi! I''d like to order KANHA Love Raspberry.', 'KANHA', ARRAY['Happy', 'Social', 'Euphoric', 'Giggly'], '[{"label": "1 pack", "price": 165}]', 21),
  ('kanha-love-fx-damiana', 'KANHA Love FX Damiana', 'kanha-love-fx-damiana', 'edible', 'FX gummy — damiana-infused, romantic vibes', 'KANHA Love FX Damiana gummies feature damiana leaf extract for an elevated romantic experience, paired with delicious flavour.', '฿165', 165, '/images/products/edibles/kanha-love-details.jpeg', ARRAY['/images/products/edibles/kanha-love-details.jpeg', '/images/products/edibles/kanha-love-raspberry.jpeg'], ARRAY['edible', 'gummy', 'fx', 'damiana', 'love'], false, true, 'Hi! I''d like to order KANHA Love FX Damiana.', 'KANHA', ARRAY['Romantic', 'Happy', 'Euphoric', 'Social'], '[{"label": "1 pack", "price": 165}]', 22),
  ('kanha-harmony-acai', 'KANHA Harmony Açaí', 'kanha-harmony-acai', 'edible', 'Balanced gummy — açaí berry, 1:1 CBD:THC harmony', 'KANHA Harmony Açaí gummies offer a perfect 1:1 CBD:THC ratio with delicious açaí berry flavour. Ideal for gentle, balanced effects.', '฿165', 165, '/images/products/edibles/kanha-harmony-acai.jpeg', '{}', ARRAY['edible', 'gummy', 'acai', 'balanced', 'cbd'], false, true, 'Hi! I''d like to order KANHA Harmony Açaí.', 'KANHA', ARRAY['Balanced', 'Calm', 'Happy', 'Gentle'], '[{"label": "1 pack", "price": 165}]', 23),
  ('kanha-cbd-tangerine', 'KANHA CBD Tangerine', 'kanha-cbd-tangerine', 'edible', 'Pure CBD gummy — tangerine citrus, zero high', 'KANHA CBD Tangerine gummies provide pure CBD benefits with bright tangerine flavour. Zero psychoactive effects — perfect for wellness seekers.', '฿165', 165, '/images/products/edibles/kanha-cbd-tangerine.jpeg', '{}', ARRAY['edible', 'gummy', 'cbd', 'tangerine', 'wellness'], false, true, 'Hi! I''d like to order KANHA CBD Tangerine.', 'KANHA', ARRAY['Calm', 'Focused', 'Relaxed', 'No High'], '[{"label": "1 pack", "price": 165}]', 24),
  ('kanha-passionfruit', 'KANHA Passionfruit', 'kanha-passionfruit', 'edible', 'Sativa gummy — tropical passionfruit, uplifting', 'KANHA Passionfruit gummies pack sweet tropical passionfruit flavour with energising sativa effects. Perfect for daytime enjoyment.', '฿165', 165, '/images/products/edibles/kanha-passionfruit.jpeg', '{}', ARRAY['edible', 'gummy', 'passionfruit', 'sativa', 'tropical'], false, true, 'Hi! I''d like to order KANHA Passionfruit.', 'KANHA', ARRAY['Energetic', 'Happy', 'Creative', 'Uplifting'], '[{"label": "1 pack", "price": 165}]', 25),
  ('kanha-tangerine-twist', 'KANHA Tangerine Twist', 'kanha-tangerine-twist', 'edible', 'Indica gummy — tangerine twist, mellow nightcap', 'KANHA Tangerine Twist gummies combine zesty tangerine with indica effects for a mellow, relaxing nightcap experience.', '฿165', 165, '/images/products/edibles/kanha-tangerine-twist.jpeg', '{}', ARRAY['edible', 'gummy', 'tangerine', 'indica', 'evening'], false, true, 'Hi! I''d like to order KANHA Tangerine Twist.', 'KANHA', ARRAY['Relaxed', 'Sleepy', 'Calm', 'Mellow'], '[{"label": "1 pack", "price": 165}]', 26),
  ('kanha-cranpomegranate', 'KANHA Cran-Pomegranate', 'kanha-cranpomegranate', 'edible', 'THC gummy — tart cran-pomegranate, great taste', 'KANHA Cran-Pomegranate gummies deliver a delicious tart berry flavour with consistent THC dosing for a reliable, enjoyable experience.', '฿165', 165, '/images/products/edibles/kanha-cranpomegranate.jpeg', '{}', ARRAY['edible', 'gummy', 'cranberry', 'pomegranate', 'thc'], false, true, 'Hi! I''d like to order KANHA Cran-Pomegranate.', 'KANHA', ARRAY['Happy', 'Relaxed', 'Euphoric', 'Giggly'], '[{"label": "1 pack", "price": 165}]', 27),
  ('kanha-belts-runtz', 'KANHA Belts Runtz', 'kanha-belts-runtz', 'edible', 'Gummy belt — Runtz flavour, fun & potent', 'KANHA Belts Runtz are fun, chewy gummy belts with the iconic Runtz candy flavour. A tasty, potent alternative to traditional gummies.', '฿165', 165, '/images/products/edibles/kanha-belts-runtz.jpeg', '{}', ARRAY['edible', 'belt', 'runtz', 'candy', 'fun'], false, true, 'Hi! I''d like to order KANHA Belts Runtz.', 'KANHA', ARRAY['Happy', 'Giggly', 'Relaxed', 'Fun'], '[{"label": "1 pack", "price": 165}]', 28);

-- ─── Products: Pre-Rolls ──────────────────
INSERT INTO products (id, name, slug, category, short_description, long_description, price_display, price_value, image, tags, featured, in_stock, line_inquiry_text, effects, sort_order) VALUES
  ('pre-roll-classic', 'Classic Pre-Roll', 'pre-roll-classic', 'pre-roll', 'Ready to smoke — premium blend, perfectly rolled', 'Hand-rolled with our premium blend. Each pre-roll is crafted for consistent burn and smooth flavour. Ready to enjoy.', '฿60', 60, '/images/preRoll.jpg', ARRAY['pre-roll', 'convenient', 'smooth'], false, true, 'Hi! I''d like to order Classic Pre-Rolls.', ARRAY['Relaxed', 'Smooth', 'Easy'], 29);

-- ─── Products: Accessories ────────────────
INSERT INTO products (id, name, slug, category, short_description, long_description, price_display, price_value, image, images, tags, featured, in_stock, line_inquiry_text, effects, price_options, sort_order) VALUES
  ('acrylic-bong-unbreakable', 'บ้องอะคริลิก ตกไม่แตก', 'acrylic-bong-unbreakable', 'accessory', 'บ้องอะคริลิก 30cm ตกไม่แตก พกพาง่าย หมุนถอดล้างได้', 'บ้องตกไม่แตก 💯 พัสดุอะคริลิก ขนาด 30cm มีอุปกรณ์ล้างบ้องให้ครบจบ สะดวกสำหรับคนที่เดินทางและทำอุปกรณ์บ้องตกบ่อย พกพาง่ายสะดวก หมุนถอดล้างได้', '฿990 / กล่อง', 990, '/images/products/bongs/acrylic-bong.jpeg', ARRAY['/images/products/bongs/acrylic-bong.jpeg', '/images/products/bongs/acrylic-bong-1.jpeg', '/images/products/bongs/acrylic-bong-2.jpeg', '/images/products/bongs/acrylic-bong-3.jpeg'], ARRAY['bong', 'acrylic', 'unbreakable', 'portable', '30cm'], true, true, 'สวัสดีค่ะ สนใจบ้องอะคริลิกตกไม่แตก', ARRAY['Portable', 'Durable', 'Easy Clean'], '[{"label": "1 กล่อง", "price": 990}]', 30);

INSERT INTO products (id, name, slug, category, short_description, long_description, price_display, price_value, image, tags, featured, in_stock, line_inquiry_text, sort_order) VALUES
  ('grinder-premium', 'Premium Grinder', 'grinder-premium', 'accessory', '4-piece metal grinder — sharp teeth, kief catcher', 'High-quality 4-piece metal grinder with razor-sharp teeth and built-in kief catcher. Essential accessory for any connoisseur.', '฿250', 250, '/images/products/grinder.jpg', ARRAY['accessory', 'grinder', 'premium'], false, true, 'Hi! I''d like to buy the Premium Grinder.', 31);
